### ISSUE TITLE
Chore: Project Setup

### ISSUE THREAD

**Issue by jkarenzi** [jkarenzi/task-master-fe#1]
### Description

- Set up project with all necessary dependencies and non-technical tools

### Tasks
- [ ] Set up react, typescript project using vite
- [ ] Set up testing environment using vitest, @testing-library/react and @testing--library/jest-dom
- [ ] Set up CI/CD using github actions
- [ ] Set up redux for global state management
- [ ] Set up linting and formatting (also set up pre commit hooks using husky)
- [ ] Install base dependencies. e,g react-router-dom, redux, and axios

### Definition of Done
- Project is correctly set up with all necessary dependencies
- Project is deployed on vercel or render
- Developer is able to run tests
- Github actions are set up correctly
- Pre commit hooks are set up correctly
