### ISSUE TITLE
Feat: Implement Authentication

### ISSUE THREAD

**Issue by jkarenzi** [jkarenzi/task-master-fe#3]
### Description

- As a user, I want to be able to create an account and log into the application, so that I can be able to access the app's features. 
- As a user, I want to be able to login with two factor authentication enabled
- As a user, I want to be able to verify my email, and also receive two factor authentication emails  

### Tasks
- [ ] Implement signup and login pages
- [ ] Implement 2FA page and email verification page
- [ ] Implement email verification and 2FA email template designs
- [ ] Integrate the above pages with backend

### Definition of Done
- User can create an account
- User can log into the application with/without 2FA enabled
- User can verify their email
- Email templates are well designed
